#!/usr/bin/env ruby
require_relative 'classroom'
require_relative 'display'

class App
  attr_accessor :people, :books

  def initialize
    @people = []
    @books = []
    @rentals = []
    @displays = Display.new(@books, @people, @rentals)
  end

  def execute
    puts 'Welcome To The School Library App'
    menu
  end

  def menu
    puts
    puts 'Please choose an option by entering a number'
    puts '1 - List All Books'
    puts '2 - List All People'
    puts '3 - Create a Person'
    puts '4 - Create a Book'
    puts '5 - Rent a Book'
    puts '6 - List All Rentals for a Given Person (requires id)'
    puts '7 - Exit'
    puts
    response = gets.chomp
    choose_action response
  end

  def choose_action(option) # rubocop:todo Metrics/CyclomaticComplexity
    case option
    when '1'
      @display.books
    when '2'
      @display.people
    when '3'
      create_person
    when '4'
      create_book
    when '5'
      create_rental
    when '6'
      @display.rentals
    when '7'
      puts 'Exit'
    end
  end

  def create_person
    puts 'Do You Want To Create a Student (1) or a Teacher (2)'
    person_response = gets.chomp

    case person_response
    when '1'
      create_student
    when '2'
      create_teacher
    else
      puts 'Please Choose 1 - Student or 2 - Teacher'
    end
  end

  def create_student
    print 'Age: '
    age_response = gets.chomp.to_i

    print 'Name: '
    name_response = gets.chomp

    print 'Has Parent Permission? [Y/N]: '
    permission_response = gets.chomp.downcase == 'y'

    student = Student.new(age: age_response, name: name_response, parent_permission: permission_response,
                          classroom: @classroom)
    @people << student

    puts "Student #{name_response} created succesfully"

    menu
  end

  def create_teacher
    print 'Age: '
    age_response = gets.chomp.to_i

    print 'Name: '
    name_response = gets.chomp

    print 'Specialization: '
    specialization_response = gets.chomp

    teacher = Teacher.new(age: age_response, name: name_response, specialization: specialization_response)

    @people << teacher

    puts "Teacher #{teacher.name} created successfully"
    menu
  end

  def create_book
    print 'Title: '
    title = gets.chomp

    print 'Author: '
    author = gets.chomp

    book = Book.new(title, author)

    @books << book

    puts "Book: '#{book.title}' created successfully"
    menu
  end

  def create_rental
    puts 'Select a Book from the Following list by number'
    @books.each_with_index { |book, i| puts "#{i} Title: #{book.title}, Author: #{book.author}" }

    book_i = gets.chomp.to_i

    puts 'Select a Person from the following list by number (NOT ID)'
    @people.each_with_index { |person, i| puts "#{i} Name: #{person.name}, Age: #{person.age}" }

    person_i = gets.chomp.to_i

    puts
    print 'Date: '
    date = gets.chomp

    rental = Rental.new(date, @books[book_i], @people[person_i])

    @rentals << rental

    puts "Book #{@books[book_i]} rented successfully by #{@people[person_i]}"

    menu
  end
end

def main
  app = App.new
  app.execute
end

main
